# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DropboxMcp < Formula
  desc "MCP server for Dropbox integration"
  homepage "https://github.com/ngs/dropbox-mcp"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ngs/dropbox-mcp/releases/download/v0.0.1/dropbox-mcp_Darwin_x86_64.tar.gz"
      sha256 "84076b7ff59c986f306fbf02580d14805cd4f35c6ad20b938633bf9cb17adf0d"

      def install
        bin.install "dropbox-mcp"
      end
    end
    on_arm do
      url "https://github.com/ngs/dropbox-mcp/releases/download/v0.0.1/dropbox-mcp_Darwin_arm64.tar.gz"
      sha256 "91ad763133e0d0160aa63dcc3c769f718d5a870801bffbc1a15fc023107d23e0"

      def install
        bin.install "dropbox-mcp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngs/dropbox-mcp/releases/download/v0.0.1/dropbox-mcp_Linux_x86_64.tar.gz"
        sha256 "16f841cab63d6dcc08da749ded1dcd5555f387933d04022a141e04203c065fe4"

        def install
          bin.install "dropbox-mcp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngs/dropbox-mcp/releases/download/v0.0.1/dropbox-mcp_Linux_arm64.tar.gz"
        sha256 "163f03d9135664b219c824c68cc38c021163a39a0a0138a14fd6da13fbd7aeb9"

        def install
          bin.install "dropbox-mcp"
        end
      end
    end
  end

  test do
    system "#{bin}/dropbox-mcp -h"
  end
end
