# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DropboxMcpServer < Formula
  desc "MCP server for Dropbox integration"
  homepage "https://github.com/ngs/dropbox-mcp-server"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ngs/dropbox-mcp-server/releases/download/v0.1.0/dropbox-mcp-server_Darwin_x86_64.tar.gz"
      sha256 "90f238de8a348da8386cd2f12d37b4749a75c41875ebe9be0516b2eca96a2bd8"

      def install
        bin.install "dropbox-mcp-server"
      end
    end
    on_arm do
      url "https://github.com/ngs/dropbox-mcp-server/releases/download/v0.1.0/dropbox-mcp-server_Darwin_arm64.tar.gz"
      sha256 "4c955b4051384cacadc63c7034540ef0c7f0ba8afdf60bc3c922556b5a2e66a2"

      def install
        bin.install "dropbox-mcp-server"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngs/dropbox-mcp-server/releases/download/v0.1.0/dropbox-mcp-server_Linux_x86_64.tar.gz"
        sha256 "240a860d35aa091bc1f9ff36e44a862244dd09c15a9615602e0026e0f8586fe5"

        def install
          bin.install "dropbox-mcp-server"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngs/dropbox-mcp-server/releases/download/v0.1.0/dropbox-mcp-server_Linux_arm64.tar.gz"
        sha256 "108aac78e264c1349948275b0dd48dede817918d45bec4ac78eebb3b099a52c9"

        def install
          bin.install "dropbox-mcp-server"
        end
      end
    end
  end

  test do
    system "#{bin}/dropbox-mcp-server -h"
  end
end
