# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoKoikoi < Formula
  desc "花札こいこいゲーム（CUI・任天堂ルール準拠）"
  homepage "https://github.com/ngs/go-koikoi"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ngs/go-koikoi/releases/download/v0.0.1/go-koikoi_0.0.1_darwin_amd64.zip"
      sha256 "105477ebf0c092f07e5fc3ec1ae5acb7782c64c6f414956fb786431f1566c6e1"

      define_method(:install) do
        bin.install "koikoi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ngs/go-koikoi/releases/download/v0.0.1/go-koikoi_0.0.1_darwin_arm64.zip"
      sha256 "342dfeddc1cde42ca44a00892ac32ac0f3f30ecffad6cf02825f911d6359b5ba"

      define_method(:install) do
        bin.install "koikoi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ngs/go-koikoi/releases/download/v0.0.1/go-koikoi_0.0.1_linux_amd64.tar.gz"
      sha256 "24848136c79a77f492cd8dbec7660c8113c30a7e97408931c6b9cc56fbe27832"
      define_method(:install) do
        bin.install "koikoi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ngs/go-koikoi/releases/download/v0.0.1/go-koikoi_0.0.1_linux_arm64.tar.gz"
      sha256 "d079ea7de1ba1346e45a9b439b3df82ce34d23f85b4d262963e0d9b2045d01ad"
      define_method(:install) do
        bin.install "koikoi"
      end
    end
  end
end
