# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoogleMcpServer < Formula
  desc "MCP server for Google APIs integration"
  homepage "https://github.com/ngs/google-mcp-server"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ngs/google-mcp-server/releases/download/v0.0.1/google-mcp-server_Darwin_x86_64.tar.gz"
      sha256 "e4691cc4d453af46dec5299e44508c7cd596504775e09153249cd045bf6091e6"

      def install
        bin.install "google-mcp-server"
      end
    end
    on_arm do
      url "https://github.com/ngs/google-mcp-server/releases/download/v0.0.1/google-mcp-server_Darwin_arm64.tar.gz"
      sha256 "c457420759def9665ff0ad46d74825ca38c2d8310b1e6df471df2b9b823f8ea7"

      def install
        bin.install "google-mcp-server"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngs/google-mcp-server/releases/download/v0.0.1/google-mcp-server_Linux_x86_64.tar.gz"
        sha256 "0385dd6bf7b54de8ff1ee4e44d73ee23892ca97eaa891bffc55115e441a09342"

        def install
          bin.install "google-mcp-server"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngs/google-mcp-server/releases/download/v0.0.1/google-mcp-server_Linux_arm64.tar.gz"
        sha256 "681426a96f92eb7215421a50e16532ee5c658ed5ca7ebf2df5dce3016d135e92"

        def install
          bin.install "google-mcp-server"
        end
      end
    end
  end

  test do
    system "#{bin}/google-mcp-server", "--version"
  end
end
