# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoogleMcpServer < Formula
  desc "MCP server for Google APIs integration"
  homepage "https://github.com/ngs/google-mcp-server"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ngs/google-mcp-server/releases/download/v0.0.1/google-mcp-server_Darwin_x86_64.tar.gz"
      sha256 "da5f322c2bc9272987bb673001e4d5f7f3070c5a622b1031a2ba1fac28c17cfc"

      def install
        bin.install "google-mcp-server"
      end
    end
    on_arm do
      url "https://github.com/ngs/google-mcp-server/releases/download/v0.0.1/google-mcp-server_Darwin_arm64.tar.gz"
      sha256 "35e3b6dd1bf4b34dec36c44585f4269677e95eb2e210b9cbe329d6554aff8646"

      def install
        bin.install "google-mcp-server"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngs/google-mcp-server/releases/download/v0.0.1/google-mcp-server_Linux_x86_64.tar.gz"
        sha256 "2d42f33dfef91a58b8e4b6396b831f5600451d53c83fdead947fe3337669108c"

        def install
          bin.install "google-mcp-server"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngs/google-mcp-server/releases/download/v0.0.1/google-mcp-server_Linux_arm64.tar.gz"
        sha256 "2644ddaa5f71589491b7a411b2a70c7d922f37a2a505918c50ad778144adf6fb"

        def install
          bin.install "google-mcp-server"
        end
      end
    end
  end

  test do
    system "#{bin}/google-mcp-server", "--version"
  end
end
