# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jplaw2epub < Formula
  desc "Convert Japanese Standard Law XML Schema into EPUB files"
  homepage "https://github.com/ngs/jplaw2epub"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ngs/jplaw2epub/releases/download/v1.0.0/jplaw2epub_Darwin_x86_64.tar.gz"
      sha256 "4791e422b0dc4b21cbacf312d851bab1d4ae858c25598458b6460e4b034a51a0"

      def install
        bin.install "jplaw2epub"
      end
    end
    on_arm do
      url "https://github.com/ngs/jplaw2epub/releases/download/v1.0.0/jplaw2epub_Darwin_arm64.tar.gz"
      sha256 "cf9be5b0fd2b1625e9cddac4b0bea105ad7af99c85234175d4a128b45fb4940e"

      def install
        bin.install "jplaw2epub"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngs/jplaw2epub/releases/download/v1.0.0/jplaw2epub_Linux_x86_64.tar.gz"
        sha256 "0251a81d99472aa098a7d60227c386db793af2e0281075b6ff78614ad7d68d41"

        def install
          bin.install "jplaw2epub"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngs/jplaw2epub/releases/download/v1.0.0/jplaw2epub_Linux_arm64.tar.gz"
        sha256 "725f995f4b4373c4641d43d4211649c116c68b8fe4aa0157a9ea1b155ce968ee"

        def install
          bin.install "jplaw2epub"
        end
      end
    end
  end

  test do
    system "#{bin}/jplaw2epub -h"
  end
end
