# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jplaw2epub < Formula
  desc "Convert Japanese Standard Law XML Schema into EPUB files"
  homepage "https://github.com/ngs/jplaw2epub"
  version "1.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ngs/jplaw2epub/releases/download/v1.2.0/jplaw2epub_Darwin_x86_64.tar.gz"
      sha256 "c0de7daf43311582f479fbf35c807230681fc503c0e80f8e27af202013d310f0"

      def install
        bin.install "jplaw2epub"
      end
    end
    on_arm do
      url "https://github.com/ngs/jplaw2epub/releases/download/v1.2.0/jplaw2epub_Darwin_arm64.tar.gz"
      sha256 "6c86bef67210b71088e994484005c9d2d4a6ffee73dc5a6f0b0c6dc3477c7390"

      def install
        bin.install "jplaw2epub"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngs/jplaw2epub/releases/download/v1.2.0/jplaw2epub_Linux_x86_64.tar.gz"
        sha256 "7b8baec54449ab667aeffa42608b5d1df5a6e6b81803b64c5fdb6d6271729126"

        def install
          bin.install "jplaw2epub"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngs/jplaw2epub/releases/download/v1.2.0/jplaw2epub_Linux_arm64.tar.gz"
        sha256 "12e0a8fdb67b64d35ac22d280f58ef43cc88866b4d5786b1ad3815516b15db0e"

        def install
          bin.install "jplaw2epub"
        end
      end
    end
  end

  test do
    system "#{bin}/jplaw2epub -h"
  end
end
