# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koikoi < Formula
  desc "花札こいこいゲーム（CUI・任天堂ルール準拠）"
  homepage "https://github.com/ngs/go-koikoi"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ngs/go-koikoi/releases/download/v0.0.6/go-koikoi_0.0.6_darwin_amd64.zip"
      sha256 "f2b4ba7820f2d79619744701558d1a824dae3ca92eaa1ad404b501425c105409"

      define_method(:install) do
        bin.install "koikoi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ngs/go-koikoi/releases/download/v0.0.6/go-koikoi_0.0.6_darwin_arm64.zip"
      sha256 "8ba9622c4e1eecd3ba16b5e74a2ad139fb437cfee6f1a9d6517148b202597401"

      define_method(:install) do
        bin.install "koikoi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ngs/go-koikoi/releases/download/v0.0.6/go-koikoi_0.0.6_linux_amd64.tar.gz"
      sha256 "bdc07e9db036b759e6f1f1cee6e55edc1b330da7ba2dbacdbe9fd9193ae858c7"
      define_method(:install) do
        bin.install "koikoi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ngs/go-koikoi/releases/download/v0.0.6/go-koikoi_0.0.6_linux_arm64.tar.gz"
      sha256 "6bbef8142744a9f0df9d7bb706b300210d59d2c0ff7e59585b25dceb1819b648"
      define_method(:install) do
        bin.install "koikoi"
      end
    end
  end
end
