# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koikoi < Formula
  desc "花札こいこいゲーム（CUI・任天堂ルール準拠）"
  homepage "https://github.com/ngs/go-koikoi"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ngs/go-koikoi/releases/download/v0.0.1/go-koikoi_0.0.1_darwin_amd64.zip"
      sha256 "4b511d669bb41c2579021380a48c7e20e8d68124d64770c47553643d1d72bb47"

      define_method(:install) do
        bin.install "koikoi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ngs/go-koikoi/releases/download/v0.0.1/go-koikoi_0.0.1_darwin_arm64.zip"
      sha256 "ae9808f50ac574aa6fd80957ab4d2ee33e9cbf821519bf69e11a30d2f9b23658"

      define_method(:install) do
        bin.install "koikoi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ngs/go-koikoi/releases/download/v0.0.1/go-koikoi_0.0.1_linux_amd64.tar.gz"
      sha256 "08f6cd7b93f8e8fe19798136f111c88c2887fab58532228af7eb7df333ae5883"
      define_method(:install) do
        bin.install "koikoi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ngs/go-koikoi/releases/download/v0.0.1/go-koikoi_0.0.1_linux_arm64.tar.gz"
      sha256 "3629744c8ad052f1761bd516a5f42d7d82813b9bfb8676d5b190ad88e7eb0152"
      define_method(:install) do
        bin.install "koikoi"
      end
    end
  end
end
