# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackBridgeMcpServer < Formula
  desc "MCP server bridging a Claude CLI session to a private Slack channel"
  homepage "https://github.com/ngs/slack-bridge-mcp-server"
  version "0.2.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ngs/slack-bridge-mcp-server/releases/download/v0.2.1/slack-bridge-mcp-server_Darwin_x86_64.tar.gz"
      sha256 "aef135b97b07c04e7bdb3392f97a767502e358d1d26908ff473932b76d06d722"

      def install
        bin.install "slack-bridge-mcp-server"
      end
    end
    on_arm do
      url "https://github.com/ngs/slack-bridge-mcp-server/releases/download/v0.2.1/slack-bridge-mcp-server_Darwin_arm64.tar.gz"
      sha256 "325a7fc5b67b988ae8addf2f18b92c4b1e2fb6fec8b53d8f3b66307a21f0c5ca"

      def install
        bin.install "slack-bridge-mcp-server"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngs/slack-bridge-mcp-server/releases/download/v0.2.1/slack-bridge-mcp-server_Linux_x86_64.tar.gz"
        sha256 "baef51da99e7b1411bb8b4e64f63b41a41311675f543f73dc4a116c4569787e6"

        def install
          bin.install "slack-bridge-mcp-server"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngs/slack-bridge-mcp-server/releases/download/v0.2.1/slack-bridge-mcp-server_Linux_arm64.tar.gz"
        sha256 "e71f54275dfa50b8d4228ed8ea2776f4bc8b796d975778c9993599cc19ae01ce"

        def install
          bin.install "slack-bridge-mcp-server"
        end
      end
    end
  end

  test do
    system "#{bin}/slack-bridge-mcp-server", "--version"
  end
end
