# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackBridgeMcpServer < Formula
  desc "MCP server bridging a Claude CLI session to a private Slack channel"
  homepage "https://github.com/ngs/slack-bridge-mcp-server"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ngs/slack-bridge-mcp-server/releases/download/v0.3.0/slack-bridge-mcp-server_Darwin_x86_64.tar.gz"
      sha256 "1c16801fec3a2f13d3f3d01fe2d41d28199950f5670d130e3de8337630b78367"

      def install
        bin.install "slack-bridge-mcp-server"
      end
    end
    on_arm do
      url "https://github.com/ngs/slack-bridge-mcp-server/releases/download/v0.3.0/slack-bridge-mcp-server_Darwin_arm64.tar.gz"
      sha256 "cb2a29363ac40e4eef8910bcfc2afbce4cda8f39e689fa96b40f18f698aa0d12"

      def install
        bin.install "slack-bridge-mcp-server"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngs/slack-bridge-mcp-server/releases/download/v0.3.0/slack-bridge-mcp-server_Linux_x86_64.tar.gz"
        sha256 "1fc0454b4dca767218ab55b3ee607f7d4c40c3227347eff180379cfb7e611c0f"

        def install
          bin.install "slack-bridge-mcp-server"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngs/slack-bridge-mcp-server/releases/download/v0.3.0/slack-bridge-mcp-server_Linux_arm64.tar.gz"
        sha256 "0f6467c10249191c52fff125070415c9aec9580bbbe79244ff784ab40aa88030"

        def install
          bin.install "slack-bridge-mcp-server"
        end
      end
    end
  end

  test do
    system "#{bin}/slack-bridge-mcp-server", "--version"
  end
end
