# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackBridgeMcpServer < Formula
  desc "MCP server bridging a Claude CLI session to a private Slack channel"
  homepage "https://github.com/ngs/slack-bridge-mcp-server"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ngs/slack-bridge-mcp-server/releases/download/v0.2.0/slack-bridge-mcp-server_Darwin_x86_64.tar.gz"
      sha256 "218644fba01a3ee274a2f119556f85c6a8d5157bcac74fc20c249c0ba82ea66f"

      def install
        bin.install "slack-bridge-mcp-server"
      end
    end
    on_arm do
      url "https://github.com/ngs/slack-bridge-mcp-server/releases/download/v0.2.0/slack-bridge-mcp-server_Darwin_arm64.tar.gz"
      sha256 "74b951a8568a3c56ca1305e25ec2dbf7f556c7b50c3a937284742514ff94aa04"

      def install
        bin.install "slack-bridge-mcp-server"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngs/slack-bridge-mcp-server/releases/download/v0.2.0/slack-bridge-mcp-server_Linux_x86_64.tar.gz"
        sha256 "3e50717507fdfdade9b5c77722b1663a10bdc5cb38a87808dc382144da07ed4b"

        def install
          bin.install "slack-bridge-mcp-server"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngs/slack-bridge-mcp-server/releases/download/v0.2.0/slack-bridge-mcp-server_Linux_arm64.tar.gz"
        sha256 "a7a8d5dd71ea65756ea2be52549afa9aa768024e850527ca063957ec3a3bb5bf"

        def install
          bin.install "slack-bridge-mcp-server"
        end
      end
    end
  end

  test do
    system "#{bin}/slack-bridge-mcp-server", "--version"
  end
end
